---
- name: Enable mod_rewrite
  command: a2enmod rewrite

- name: Install Rails-style virtual host
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/{{server_name}}.conf
  when: ssl|bool != True

- name: Make sure the SSL certificate is installed
  copy: src={{ local_certificate_file }} mode=0644 group=root owner=root dest="/etc/ssl/{{ local_certificate_file | basename }}"
  when: (ssl | bool) and (local_certificate_file is defined)

- name: Make sure the SSL certificate private key is installed
  copy: src={{ local_certificate_key_file }} mode=0640 owner=root group=ssl-cert dest="/etc/ssl/private/{{ local_certificate_key_file | basename }}"
  when: (ssl | bool) and (local_certificate_key_file is defined)

- name: Make sure the SSL certificate chain file is installed
  copy: src={{ local_certificate_chain_file }} mode=0644 group=root owner=root dest="/etc/ssl/{{ local_certificate_chain_file | basename }}"
  when: (ssl | bool) and (local_certificate_chain_file is defined)

- name: Install Rails-style virtual host (with SSL)
  template: src=vhost.ssl.conf.j2 dest="/etc/apache2/sites-available/{{server_name}}.ssl.conf"
  when: ssl | bool

- name: Enable Rails-style virtual host
  command: a2ensite {{ server_name }}
  notify: reload apache
  when: (ssl == False) and ((enabled | bool) == True)

- name: Enable Rails-style virtual host (with SSL)
  command: "a2ensite {{ server_name }}.ssl"
  notify: reload apache
  when: (ssl | bool) and (enabled | bool)

- name: Disable Rails-style virtual host
  command: a2dissite {{ server_name }}
  notify: reload apache
  when: not enabled

- name: Disable Rails-style virtual host (with SSL)
  command: "a2dissite {{ server_name }}.ssl"
  notify: reload apache
  when: (ssl | bool) and not enabled

- name: Install a redirect virtual host from non-SSL to SSL
  template: src=vhost.sslredirect.conf.j2 dest="/etc/apache2/sites-available/{{server_name}}.sslredirect.conf"
  when: ssl|bool and sslredirect|bool

- name: Enable redirect virtual host
  command: "a2ensite {{ server_name }}.sslredirect"
  notify: reload apache
  when: ssl|bool and sslredirect|bool
